### ISSUE TITLE
Une question à propos de l'immigration de tensorflow.1 vers tensorflow.2 de votre code

### ISSUE THREAD

**Issue by hamzaelouiaazzani** [boberle/cofr#6]
Bonjour Mr. Bruno, j'espère que le présent message vous trouvera en bonne et parfaite santé. 
J'ai une petite question s'il vous plaît, est-ce que si je fait l'immigration de votre code COFR du tensorflow.1 vers tensorflow.2 ça va compiler le code avec succès ?
Cordialement,

**Comment by boberle** [comment]
Hello Hamza, There are quite some changes between the two versions of TensorFlow, so it would be pretty tedious to change the version, and the best way is, in my opinion, to use TF1. It would be possible though, but I don't plan to do it this on this project. This is why I'm closing this issue.

Hello Hamza, Il y a pas mal de changements entre les deux versions de TF. Faire la migration serait plutôt compliqué et je conseille de rester à TF1. Cependant, je pense que ce serait possible, mais je n'ai pas l'intention de le faire sur ce projet. C'est la raison pour laquelle je ferme l'issue.
